version: "3.4"
##Author Sebin Sebastian sebin.sbtn@gmail.com
services:
  DB:
      image: mysql:5.7
      ports:
          - "3307:3306"
      volumes:
          - ./db:/var/lib/mysql
      restart: always
      environment:
            MYSQL_ROOT_PASSWORD: 'Password@1'
            MYSQL_DATABASE: 'logindetails'
            MYSQL_USER: 'sshuser'
            MYSQL_PASSWORD: 'Password@1'

  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: sshuser
            MYSQL_PASSWORD: Password@1
            MYSQL_ROOT_PASSWORD: Password@1
     ports:
            - 82:80
     restart: always
     links:
            - DB
  web:
    build: .
    volumes:
      - "./web:/var/www/html"
    ports:
    - "81:80"
    tty: true
    stdin_open: true
    restart: always
    links:
            - DB

  tcp_server:
    build: python/.
    volumes:
      - "./python:/usr/src/app"
    ports:
    - "1492:1492"
    tty: true
    stdin_open: true
    restart: always
    links:
            - DB
